#ifndef Libreries_h
#define Libreries_h

// c++ headers
#include <iostream>
#include <string>    
#include <utility>
#include <sstream> 
#include <algorithm> 
#include <stdio.h> 
#include <stdlib.h> 
#include <vector> 
#include <fstream> 
#include <cmath>
#include <math.h> 
#include <cstdlib>
#include <bitset>
#include <map>
#include <memory>

// ROOT headers
#include <TGraphAsymmErrors.h>
#include <TEfficiency.h>
#include <TSystem.h>
#include <TProof.h>
#include <TEnv.h>
#include <TFileCollection.h>
#include <THashList.h>
#include <TFile.h>
#include <TTree.h>
#include <TChain.h>
#include <TH1D.h> 
#include <TROOT.h>
#include <TParticle.h>
#include "TRandom3.h"
#include <TH2.h> 
#include <TF1.h> 
#include <TF2.h> 
#include <TH3.h> 
#include "TEllipse.h"
#include <THStack.h> 
#include <TStyle.h> 
#include <TGraph.h> 
#include <TGraph2D.h> 
#include <TGraphErrors.h> 
#include <TCanvas.h> 
#include "TPaveText.h"
#include <TLegend.h> 
#include <TGaxis.h> 
#include <TString.h> 
#include <TSystem.h> 
#include <TColor.h> 
#include <TLine.h> 
#include <TExec.h> 
#include <TFitResultPtr.h> 
#include <TFitResult.h> 
#include <TLatex.h> 
#include <TMath.h>
#include <TKey.h>
#include <TLorentzVector.h>
#include <TRandom2.h>
#include <TH1.h>
#include <TVirtualFitter.h>
#include <TPolyLine3D.h>
#include <TPaletteAxis.h>
#include <Math/Vector3D.h>
#include "RooFFTConvPdf.h"
#include "RooAbsCachedPdf.h"
#include "RooRealVar.h"
#include "RooDataHist.h"
#include "RooPlot.h"
#include "RooGaussian.h"
#include "RooFitResult.h"
#include "RooArgList.h"
#include "RooPolynomial.h"
#include "RooAddPdf.h"


#endif